rudak_user_admin_user:
    resource: "@RudakUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

rudakUser_profile:
    pattern: /mon-profil
    defaults: { _controller: RudakUserBundle:Default:profile }

index:
    pattern:     /index
    defaults: { _controller: RudakUserBundle:Default:index }

record_new:
    pattern:     /record-new-user
    defaults: { _controller: RudakUserBundle:Record:new }

record_create:
    pattern:     /create-user
    defaults: { _controller: RudakUserBundle:Record:create }
    requirements:
        _method: POST

record_validing_email:
    pattern:     /email-validation/{hash}
    defaults: { _controller: RudakUserBundle:Record:validation }
    requirements:
        hash: "[a-z\d]+"

rudakUser_lost_pwd:
    pattern: /mot-de-passe-perdu
    defaults: { _controller: RudakUserBundle:Password:lost }

rudakUser_lost_pwd_find:
    pattern: /retrouver-utilisateur
    defaults: { _controller: RudakUserBundle:Password:findUser }
    requirements:
        _method: POST

rudakUser_reinit_mail_answer:
    pattern: /reinitialisation-mot-de-passe/{hash}
    defaults: { _controller: RudakUserBundle:Password:emailAnswer }
    requirements:
        hash: "[a-z\d]+"

rudakUser_password_lost_reinit:
    pattern: /enregistrer-nouveau-mot-de-passe
    defaults: { _controller: RudakUserBundle:Password:emailAnswer }
    requirements:
        _method: POST

rudakUser_pwd_modification:
    pattern: /modifier-mot-de-passe
    defaults: { _controller: RudakUserBundle:Password:changePassword }

rudakUser_email_modification:
    pattern: /modifier-mon-email
    defaults: { _controller: RudakUserBundle:Email:changeEmail }

rudakUser_email_change_confirmation:
    pattern: /confirmer-nouvelle-adresse-email/{hash}
    defaults: { _controller: RudakUserBundle:Email:confirmationEmail }
