index:
    pattern:     /index
    defaults: { _controller: RudakUserBundle:Default:index }


record_new:
    pattern:     /record-new-user
    defaults: { _controller: RudakUserBundle:Record:new }

record_create:
    pattern:     /create-user
    defaults: { _controller: RudakUserBundle:Record:create }
    requirements:
        _method: POST

record_validing_email:
    pattern:     /email-validation/{hash}
    defaults: { _controller: RudakUserBundle:Record:validation }
    requirements:
        hash: "[a-z\d]+"