rudak_user_admin_user:
    resource: "@RudakUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user
rudak_user_logged:
    resource: "@RudakUserBundle/Resources/config/routing/logged.yml"
    prefix:   /user

index:
    path:     /index
    defaults: { _controller: RudakUserBundle:Default:index }

record_new:
    path:     /record-new-user
    defaults: { _controller: RudakUserBundle:Record:new }

record_create:
    path:     /create-user
    defaults: { _controller: RudakUserBundle:Record:create }

record_validing_email:
    path:     /email-validation/{hash}
    defaults: { _controller: RudakUserBundle:Record:validation }
    requirements:
        hash: "[a-z\d]+"

rudakUser_lost_pwd:
    path: /mot-de-passe-perdu
    defaults: { _controller: RudakUserBundle:Password:lost }

rudakUser_lost_pwd_find:
    path: /retrouver-utilisateur
    defaults: { _controller: RudakUserBundle:Password:findUser }
    requirements:
    methods: [POST]

rudakUser_autogen_pwd_answer:
    path: /autogen-mot-de-passe/{hash}
    defaults: { _controller: RudakUserBundle:Password:autoGenAnswer }
    requirements:
        hash: "[a-z\d]+"

rudakUser_reinit_mail_answer:
    path: /reinitialisation-mot-de-passe/{hash}
    defaults: { _controller: RudakUserBundle:Password:emailAnswer }
    requirements:
        hash: "[a-z\d]+"


rudakUser_email_change_confirmation:
    path: /confirmer-nouvelle-adresse-email/{hash}
    defaults: { _controller: RudakUserBundle:Email:confirmationEmail }
