services:
    rudak.user.login:
        class: Rudak\UserBundle\Listener\LoginListener
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
    rudak_user.handler.post_record:
        class: Rudak\UserBundle\Handler\PostRecordHandler
        arguments: [@mailer,@templating,@router]
    rudak.user.listener.post.record:
        class: Rudak\UserBundle\Listener\PostRecordListener
        arguments: [@rudak_user.handler.post_record]
        tags:
            - { name: kernel.event_listener, event: rudak_user.record, method: updateUser }
