services:
    rudak.user.login:
        class: Rudak\UserBundle\Listener\LoginListener
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }