rudakUser_profile:
    path: /mon-profil
    defaults: { _controller: RudakUserBundle:Default:profile }

# MODIFIER MOT DE PASSE
rudakUser_pwd_modification:
    path: /modifier-mot-de-passe
    defaults: { _controller: RudakUserBundle:Password:changePassword }

rudakUser_password_lost_reinit:
    path: /enregistrer-nouveau-mot-de-passe
    defaults: { _controller: RudakUserBundle:Password:emailAnswer }
    methods: [POST]

# MODIFIER EMAIL
rudakUser_email_modification:
    path: /modifier-mon-email
    defaults: { _controller: RudakUserBundle:Email:changeEmail }


